//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4971
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： John
//             Created Time： 2012/7/22 16:22:24
// 
// -------------------------------------------------------------
namespace Entity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class tb_AutoSwitchEntity : EntityObject
    {
        
        /// <summary>id</summary>
        public const string @__ID = "id";
        
        /// <summary>switch</summary>
        public const string @__SWITCH = "switch";
        
        /// <summary>Description</summary>
        public const string @__DESCRIPTION = "Description";
        
        private int m_id;
        
        private string m_switch;
        
        private string m_Description;
        
        /// <summary>构造函数</summary>
        public tb_AutoSwitchEntity()
        {
        }
        
        /// <summary>属性id </summary>
        public int id
        {
            get
            {
                return this.m_id;
            }
            set
            {
                this.m_id = value;
            }
        }
        
        /// <summary>属性switch </summary>
        public string @switch
        {
            get
            {
                return this.m_switch;
            }
            set
            {
                this.m_switch = value;
            }
        }
        
        /// <summary>属性Description </summary>
        public string Description
        {
            get
            {
                return this.m_Description;
            }
            set
            {
                this.m_Description = value;
            }
        }
    }
    
    /// tb_AutoSwitchEntity执行类
    public abstract class tb_AutoSwitchEntityAction
    {
        
        private tb_AutoSwitchEntityAction()
        {
        }
        
        public static void Save(tb_AutoSwitchEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static tb_AutoSwitchEntity RetrieveAtb_AutoSwitchEntity(int id)
        {
            tb_AutoSwitchEntity obj=new tb_AutoSwitchEntity();
            obj.id=id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer Retrievetb_AutoSwitchEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_AutoSwitchEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable Gettb_AutoSwitchEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_AutoSwitchEntity));
            return rc.AsDataTable();
        }
    }
}
