//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4971
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： John
//             Created Time： 2012/7/22 16:22:24
// 
// -------------------------------------------------------------
namespace Entity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class tb_GoldTimeslotEntity : EntityObject
    {
        
        /// <summary>id</summary>
        public const string @__ID = "id";
        
        /// <summary>TimeslotName</summary>
        public const string @__TIMESLOTNAME = "TimeslotName";
        
        /// <summary>startTime</summary>
        public const string @__STARTTIME = "startTime";
        
        /// <summary>endTime</summary>
        public const string @__ENDTIME = "endTime";
        
        /// <summary>created</summary>
        public const string @__CREATED = "created";
        
        /// <summary>user_id</summary>
        public const string @__USER_ID = "user_id";
        
        private int m_id;
        
        private string m_TimeslotName;
        
        private System.DateTime m_startTime = DateTime.MinValue;
        
        private System.DateTime m_endTime = DateTime.MinValue;
        
        private System.DateTime m_created = DateTime.MinValue;
        
        private int m_user_id;
        
        /// <summary>构造函数</summary>
        public tb_GoldTimeslotEntity()
        {
        }
        
        /// <summary>属性id </summary>
        public int id
        {
            get
            {
                return this.m_id;
            }
            set
            {
                this.m_id = value;
            }
        }
        
        /// <summary>属性TimeslotName </summary>
        public string TimeslotName
        {
            get
            {
                return this.m_TimeslotName;
            }
            set
            {
                this.m_TimeslotName = value;
            }
        }
        
        /// <summary>属性startTime </summary>
        public System.DateTime startTime
        {
            get
            {
                return this.m_startTime;
            }
            set
            {
                this.m_startTime = value;
            }
        }
        
        /// <summary>属性endTime </summary>
        public System.DateTime endTime
        {
            get
            {
                return this.m_endTime;
            }
            set
            {
                this.m_endTime = value;
            }
        }
        
        /// <summary>属性created </summary>
        public System.DateTime created
        {
            get
            {
                return this.m_created;
            }
            set
            {
                this.m_created = value;
            }
        }
        
        /// <summary>属性user_id </summary>
        public int user_id
        {
            get
            {
                return this.m_user_id;
            }
            set
            {
                this.m_user_id = value;
            }
        }
    }
    
    /// tb_GoldTimeslotEntity执行类
    public abstract class tb_GoldTimeslotEntityAction
    {
        
        private tb_GoldTimeslotEntityAction()
        {
        }
        
        public static void Save(tb_GoldTimeslotEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static tb_GoldTimeslotEntity RetrieveAtb_GoldTimeslotEntity(int id)
        {
            tb_GoldTimeslotEntity obj=new tb_GoldTimeslotEntity();
            obj.id=id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer Retrievetb_GoldTimeslotEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_GoldTimeslotEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable Gettb_GoldTimeslotEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_GoldTimeslotEntity));
            return rc.AsDataTable();
        }
    }
}
