//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4971
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： John
//             Created Time： 2012/7/22 16:22:24
// 
// -------------------------------------------------------------
namespace Entity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class tb_GoldTimeSchemeEntity : EntityObject
    {
        
        /// <summary>id</summary>
        public const string @__ID = "id";
        
        /// <summary>SchemeName</summary>
        public const string @__SCHEMENAME = "SchemeName";
        
        /// <summary>user_id</summary>
        public const string @__USER_ID = "user_id";
        
        /// <summary>created</summary>
        public const string @__CREATED = "created";
        
        /// <summary>interval</summary>
        public const string @__INTERVAL = "interval";
        
        private int m_id;
        
        private string m_SchemeName;
        
        private int m_user_id;
        
        private System.DateTime m_created = DateTime.MinValue;
        
        private int m_interval;
        
        /// <summary>构造函数</summary>
        public tb_GoldTimeSchemeEntity()
        {
        }
        
        /// <summary>属性id </summary>
        public int id
        {
            get
            {
                return this.m_id;
            }
            set
            {
                this.m_id = value;
            }
        }
        
        /// <summary>属性SchemeName </summary>
        public string SchemeName
        {
            get
            {
                return this.m_SchemeName;
            }
            set
            {
                this.m_SchemeName = value;
            }
        }
        
        /// <summary>属性user_id </summary>
        public int user_id
        {
            get
            {
                return this.m_user_id;
            }
            set
            {
                this.m_user_id = value;
            }
        }
        
        /// <summary>属性created </summary>
        public System.DateTime created
        {
            get
            {
                return this.m_created;
            }
            set
            {
                this.m_created = value;
            }
        }
        
        /// <summary>属性interval </summary>
        public int interval
        {
            get
            {
                return this.m_interval;
            }
            set
            {
                this.m_interval = value;
            }
        }
    }
    
    /// tb_GoldTimeSchemeEntity执行类
    public abstract class tb_GoldTimeSchemeEntityAction
    {
        
        private tb_GoldTimeSchemeEntityAction()
        {
        }
        
        public static void Save(tb_GoldTimeSchemeEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static tb_GoldTimeSchemeEntity RetrieveAtb_GoldTimeSchemeEntity(int id)
        {
            tb_GoldTimeSchemeEntity obj=new tb_GoldTimeSchemeEntity();
            obj.id=id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer Retrievetb_GoldTimeSchemeEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_GoldTimeSchemeEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable Gettb_GoldTimeSchemeEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_GoldTimeSchemeEntity));
            return rc.AsDataTable();
        }
    }
}
