//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4971
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： John
//             Created Time： 2012/7/22 16:22:24
// 
// -------------------------------------------------------------
namespace Entity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class tb_GoldTimeslotSchemeDetailsEntity : EntityObject
    {
        
        /// <summary>id</summary>
        public const string @__ID = "id";
        
        /// <summary>GT_id</summary>
        public const string @__GT_ID = "GT_id";
        
        /// <summary>dayOfWeek</summary>
        public const string @__DAYOFWEEK = "dayOfWeek";
        
        /// <summary>Scheme_id</summary>
        public const string @__SCHEME_ID = "Scheme_id";
        
        private int m_id;
        
        private int m_GT_id;
        
        private int m_dayOfWeek;
        
        private int m_Scheme_id;
        
        /// <summary>构造函数</summary>
        public tb_GoldTimeslotSchemeDetailsEntity()
        {
        }
        
        /// <summary>属性id </summary>
        public int id
        {
            get
            {
                return this.m_id;
            }
            set
            {
                this.m_id = value;
            }
        }
        
        /// <summary>属性GT_id </summary>
        public int GT_id
        {
            get
            {
                return this.m_GT_id;
            }
            set
            {
                this.m_GT_id = value;
            }
        }
        
        /// <summary>属性dayOfWeek </summary>
        public int dayOfWeek
        {
            get
            {
                return this.m_dayOfWeek;
            }
            set
            {
                this.m_dayOfWeek = value;
            }
        }
        
        /// <summary>属性Scheme_id </summary>
        public int Scheme_id
        {
            get
            {
                return this.m_Scheme_id;
            }
            set
            {
                this.m_Scheme_id = value;
            }
        }
    }
    
    /// tb_GoldTimeslotSchemeDetailsEntity执行类
    public abstract class tb_GoldTimeslotSchemeDetailsEntityAction
    {
        
        private tb_GoldTimeslotSchemeDetailsEntityAction()
        {
        }
        
        public static void Save(tb_GoldTimeslotSchemeDetailsEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static tb_GoldTimeslotSchemeDetailsEntity RetrieveAtb_GoldTimeslotSchemeDetailsEntity(int id)
        {
            tb_GoldTimeslotSchemeDetailsEntity obj=new tb_GoldTimeslotSchemeDetailsEntity();
            obj.id=id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer Retrievetb_GoldTimeslotSchemeDetailsEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_GoldTimeslotSchemeDetailsEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable Gettb_GoldTimeslotSchemeDetailsEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_GoldTimeslotSchemeDetailsEntity));
            return rc.AsDataTable();
        }
    }
}
