//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4971
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： John
//             Created Time： 2012/7/22 16:22:24
// 
// -------------------------------------------------------------
namespace Entity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class tb_InGoldTimeItemsEntity : EntityObject
    {
        
        /// <summary>id</summary>
        public const string @__ID = "id";
        
        /// <summary>num_iid</summary>
        public const string @__NUM_IID = "num_iid";
        
        /// <summary>created</summary>
        public const string @__CREATED = "created";
        
        /// <summary>nick</summary>
        public const string @__NICK = "nick";
        
        private int m_id;
        
        private long m_num_iid;
        
        private System.DateTime m_created = DateTime.MinValue;
        
        private string m_nick;
        
        /// <summary>构造函数</summary>
        public tb_InGoldTimeItemsEntity()
        {
        }
        
        /// <summary>属性id </summary>
        public int id
        {
            get
            {
                return this.m_id;
            }
            set
            {
                this.m_id = value;
            }
        }
        
        /// <summary>属性num_iid </summary>
        public long num_iid
        {
            get
            {
                return this.m_num_iid;
            }
            set
            {
                this.m_num_iid = value;
            }
        }
        
        /// <summary>属性created </summary>
        public System.DateTime created
        {
            get
            {
                return this.m_created;
            }
            set
            {
                this.m_created = value;
            }
        }
        
        /// <summary>属性nick </summary>
        public string nick
        {
            get
            {
                return this.m_nick;
            }
            set
            {
                this.m_nick = value;
            }
        }
    }
    
    /// tb_InGoldTimeItemsEntity执行类
    public abstract class tb_InGoldTimeItemsEntityAction
    {
        
        private tb_InGoldTimeItemsEntityAction()
        {
        }
        
        public static void Save(tb_InGoldTimeItemsEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static tb_InGoldTimeItemsEntity RetrieveAtb_InGoldTimeItemsEntity(int id)
        {
            tb_InGoldTimeItemsEntity obj=new tb_InGoldTimeItemsEntity();
            obj.id=id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer Retrievetb_InGoldTimeItemsEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_InGoldTimeItemsEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable Gettb_InGoldTimeItemsEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_InGoldTimeItemsEntity));
            return rc.AsDataTable();
        }
    }
}
