//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4971
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： John
//             Created Time： 2012/7/22 16:22:24
// 
// -------------------------------------------------------------
namespace Entity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class tb_ScheduleRelistQueueEntity : EntityObject
    {
        
        /// <summary>id</summary>
        public const string @__ID = "id";
        
        /// <summary>num_iid</summary>
        public const string @__NUM_IID = "num_iid";
        
        /// <summary>Schedule</summary>
        public const string @__SCHEDULE = "Schedule";
        
        /// <summary>item_title</summary>
        public const string @__ITEM_TITLE = "item_title";
        
        /// <summary>created</summary>
        public const string @__CREATED = "created";
        
        /// <summary>user_id</summary>
        public const string @__USER_ID = "user_id";
        
        /// <summary>state</summary>
        public const string @__STATE = "state";
        
        private int m_id;
        
        private long m_num_iid;
        
        private System.DateTime m_Schedule = DateTime.MinValue;
        
        private string m_item_title;
        
        private System.DateTime m_created = DateTime.MinValue;
        
        private int m_user_id;
        
        private bool m_state;
        
        /// <summary>构造函数</summary>
        public tb_ScheduleRelistQueueEntity()
        {
        }
        
        /// <summary>属性id </summary>
        public int id
        {
            get
            {
                return this.m_id;
            }
            set
            {
                this.m_id = value;
            }
        }
        
        /// <summary>属性num_iid </summary>
        public long num_iid
        {
            get
            {
                return this.m_num_iid;
            }
            set
            {
                this.m_num_iid = value;
            }
        }
        
        /// <summary>属性Schedule </summary>
        public System.DateTime Schedule
        {
            get
            {
                return this.m_Schedule;
            }
            set
            {
                this.m_Schedule = value;
            }
        }
        
        /// <summary>属性item_title </summary>
        public string item_title
        {
            get
            {
                return this.m_item_title;
            }
            set
            {
                this.m_item_title = value;
            }
        }
        
        /// <summary>属性created </summary>
        public System.DateTime created
        {
            get
            {
                return this.m_created;
            }
            set
            {
                this.m_created = value;
            }
        }
        
        /// <summary>属性user_id </summary>
        public int user_id
        {
            get
            {
                return this.m_user_id;
            }
            set
            {
                this.m_user_id = value;
            }
        }
        
        /// <summary>属性state </summary>
        public bool state
        {
            get
            {
                return this.m_state;
            }
            set
            {
                this.m_state = value;
            }
        }
    }
    
    /// tb_ScheduleRelistQueueEntity执行类
    public abstract class tb_ScheduleRelistQueueEntityAction
    {
        
        private tb_ScheduleRelistQueueEntityAction()
        {
        }
        
        public static void Save(tb_ScheduleRelistQueueEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static tb_ScheduleRelistQueueEntity RetrieveAtb_ScheduleRelistQueueEntity(int id)
        {
            tb_ScheduleRelistQueueEntity obj=new tb_ScheduleRelistQueueEntity();
            obj.id=id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer Retrievetb_ScheduleRelistQueueEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_ScheduleRelistQueueEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable Gettb_ScheduleRelistQueueEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_ScheduleRelistQueueEntity));
            return rc.AsDataTable();
        }
    }
}
