//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4971
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： John
//             Created Time： 2012/7/22 16:22:24
// 
// -------------------------------------------------------------
namespace Entity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class tb_SwitchPropertyEntity : EntityObject
    {
        
        /// <summary>id</summary>
        public const string @__ID = "id";
        
        /// <summary>switch_id</summary>
        public const string @__SWITCH_ID = "switch_id";
        
        /// <summary>proName</summary>
        public const string @__PRONAME = "proName";
        
        /// <summary>Description</summary>
        public const string @__DESCRIPTION = "Description";
        
        private int m_id;
        
        private int m_switch_id;
        
        private string m_proName;
        
        private string m_Description;
        
        /// <summary>构造函数</summary>
        public tb_SwitchPropertyEntity()
        {
        }
        
        /// <summary>属性id </summary>
        public int id
        {
            get
            {
                return this.m_id;
            }
            set
            {
                this.m_id = value;
            }
        }
        
        /// <summary>属性switch_id </summary>
        public int switch_id
        {
            get
            {
                return this.m_switch_id;
            }
            set
            {
                this.m_switch_id = value;
            }
        }
        
        /// <summary>属性proName </summary>
        public string proName
        {
            get
            {
                return this.m_proName;
            }
            set
            {
                this.m_proName = value;
            }
        }
        
        /// <summary>属性Description </summary>
        public string Description
        {
            get
            {
                return this.m_Description;
            }
            set
            {
                this.m_Description = value;
            }
        }
    }
    
    /// tb_SwitchPropertyEntity执行类
    public abstract class tb_SwitchPropertyEntityAction
    {
        
        private tb_SwitchPropertyEntityAction()
        {
        }
        
        public static void Save(tb_SwitchPropertyEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static tb_SwitchPropertyEntity RetrieveAtb_SwitchPropertyEntity(int id)
        {
            tb_SwitchPropertyEntity obj=new tb_SwitchPropertyEntity();
            obj.id=id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer Retrievetb_SwitchPropertyEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_SwitchPropertyEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable Gettb_SwitchPropertyEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_SwitchPropertyEntity));
            return rc.AsDataTable();
        }
    }
}
