//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4971
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： John
//             Created Time： 2012/7/22 16:22:24
// 
// -------------------------------------------------------------
namespace Entity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class tb_UserEntity : EntityObject
    {
        
        /// <summary>id</summary>
        public const string @__ID = "id";
        
        /// <summary>nick</summary>
        public const string @__NICK = "nick";
        
        /// <summary>email</summary>
        public const string @__EMAIL = "email";
        
        /// <summary>syslevel</summary>
        public const string @__SYSLEVEL = "syslevel";
        
        /// <summary>authEndTime</summary>
        public const string @__AUTHENDTIME = "authEndTime";
        
        /// <summary>created</summary>
        public const string @__CREATED = "created";
        
        /// <summary>type</summary>
        public const string @__TYPE = "type";
        
        /// <summary>SessionKey</summary>
        public const string @__SESSIONKEY = "SessionKey";
        
        private int m_id;
        
        private string m_nick;
        
        private string m_email;
        
        private string m_syslevel;
        
        private System.DateTime m_authEndTime = DateTime.MinValue;
        
        private System.DateTime m_created = DateTime.MinValue;
        
        private string m_type;
        
        private string m_SessionKey;
        
        /// <summary>构造函数</summary>
        public tb_UserEntity()
        {
        }
        
        /// <summary>属性id </summary>
        public int id
        {
            get
            {
                return this.m_id;
            }
            set
            {
                this.m_id = value;
            }
        }
        
        /// <summary>属性nick </summary>
        public string nick
        {
            get
            {
                return this.m_nick;
            }
            set
            {
                this.m_nick = value;
            }
        }
        
        /// <summary>属性email </summary>
        public string email
        {
            get
            {
                return this.m_email;
            }
            set
            {
                this.m_email = value;
            }
        }
        
        /// <summary>属性syslevel </summary>
        public string syslevel
        {
            get
            {
                return this.m_syslevel;
            }
            set
            {
                this.m_syslevel = value;
            }
        }
        
        /// <summary>属性authEndTime </summary>
        public System.DateTime authEndTime
        {
            get
            {
                return this.m_authEndTime;
            }
            set
            {
                this.m_authEndTime = value;
            }
        }
        
        /// <summary>属性created </summary>
        public System.DateTime created
        {
            get
            {
                return this.m_created;
            }
            set
            {
                this.m_created = value;
            }
        }
        
        /// <summary>属性type </summary>
        public string type
        {
            get
            {
                return this.m_type;
            }
            set
            {
                this.m_type = value;
            }
        }
        
        /// <summary>属性SessionKey </summary>
        public string SessionKey
        {
            get
            {
                return this.m_SessionKey;
            }
            set
            {
                this.m_SessionKey = value;
            }
        }
    }
    
    /// tb_UserEntity执行类
    public abstract class tb_UserEntityAction
    {
        
        private tb_UserEntityAction()
        {
        }
        
        public static void Save(tb_UserEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static tb_UserEntity RetrieveAtb_UserEntity(int id)
        {
            tb_UserEntity obj=new tb_UserEntity();
            obj.id=id;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer Retrievetb_UserEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_UserEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable Gettb_UserEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(tb_UserEntity));
            return rc.AsDataTable();
        }
    }
}
